### ISSUE TITLE
TypeError: must be str, not bytes

### ISSUE THREAD

**Issue by muzihuole** [lixucuhk/adversarial-attack-on-GMM-i-vector-based-speaker-verification-systems#5]
你好，当我在x-vector-mfcc目录下运行./run.sh时，当进行stage1时，发生了错误。如下面所示

```
./run.sh --stage 1
stage 1, augment the Voxceleb1 data.
steps/data/reverberate_data_dir.py --rir-set-parameters 0.5, RIRS_NOISES/simulated_rirs/smallroom/rir_list --rir-set-parameters 0.5, RIRS_NOISES/simulated_rirs/mediumroom/rir_list --speech-rvb-probability 1 --pointsource-noise-addition-probability 0 --isotropic-noise-addition-probability 0 --num-replications 1 --source-sampling-rate 16000 data/train data/train_reverb
Number of RIRs is 40000
Traceback (most recent call last):
  File "steps/data/reverberate_data_dir.py", line 676, in <module>
    main()
  File "steps/data/reverberate_data_dir.py", line 669, in main
    max_noises_per_minute = args.max_noises_per_minute)
  File "steps/data/reverberate_data_dir.py", line 449, in create_reverberated_copy
    data_lib.RunKaldiCommand("utils/validate_data_dir.sh --no-feats --no-text {output_dir}".format(output_dir = output_dir))
  File "steps/data/data_dir_manipulation_lib.py", line 14, in RunKaldiCommand
    raise Exception("There was an error while running the command {0}\n".format(command)+"-"*10+"\n"+stderr)
TypeError: must be str, not bytes
```
我尝试了几次，仍不知道该如何调整，希望得到您的答复，谢谢！

**Comment by lixucuhk** [comment]
您好，感谢您对我们工作的兴趣！
您的这个错误我没有遇到过，建议您可以尝试以下两种方式，看看能不能解决：
1）run.sh这个文件要顺序执行的，在执行stage1前，要先执行stage0；
2）建议您仔细对比以下您执行的stage1代码和这里提供的代码是否完全一致，这段代码其实是kaldi里面训练xvector模型的官方代码。抱歉，我在执行时没有遇到类似的错误。所以建议您再核对一下代码，看看您是否改过哪里。
谢谢！！！

**Comment by muzihuole** [comment]
非常感谢您的回复！
我将/egs/voxceleb/v1/steps/data目录下的reverberate_data_dir.py和data_dir_manipulation_lib.py替换了x-vector-mfcc目录下的相应文件，使得stage1可以运行。
再次对您的回复表示感谢！
